/*
 * This source file was generated by the Gradle 'init' task
 */
package com.adferdv.ktile

import io.kotest.core.spec.style.StringSpec
import io.kotest.matchers.shouldBe

class AppTest :
    StringSpec({
        "app should return greeting" {
            val classUnderTest = App()
            classUnderTest.greeting shouldBe "Hello World!"
        }
    })
