name: PR Pipeline

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/ci-build.yaml

  macos-build:
    runs-on: macos-latest
    steps:
      - uses: ./.github/actions/ci-build.yaml